plugins {
    id 'application'
    id 'buildlogic.java-conventions'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.apache.kafka:kafka-clients:4.1.0'
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'ch.qos.logback:logback-classic:1.4.11'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
    implementation "org.apache.commons:commons-lang3:3.14.0"
    testImplementation 'org.testcontainers:kafka:1.21.3'
}

test {
    useJUnitPlatform()
}

