prometheusPort: 8181

kafkaConfig:
  bootstrapServers: "localhost:9092"
  groupId: "consumer-group-1"

parquetWriterConf:
  networkLogsTopic: "logs"
  hdfsDirPath: "/net-logs"
  parquetSizeLimit: 20
  hdfsUrl: "hdfs://localhost:9000"
  workerNumber: 3
  pageSize: 1048576      # 1 MB
  blockSize: 134217728   # 128 MB
  parquetTimeout: 5
