
kafkaConfig:
  bootstrapServers: "localhost:9092"
  groupId: "consumer-group-1"

parquetWriterConf:
  networkLogsTopic: "network-logs"
  hdfsDirPath: "hdfs://127.0.0.1:9000/data"
  parquetSizeLimit: 50
  hdfsUrl: "hdfs://localhost:9000"
  workerNumber: 2

queueCapacity: 1000
