package org.shahin.utils;

public enum EnrichmentError {
    SOURCE_ADDRESS_REGEX_PROBLEM,
    SOURCE_ADDRESS_NULL_PROBLEM,
    DESTINATION_ADDRESS_REGEX_PROBLEM,
    DESTINATION_ADDRESS_NULL_PROBLEM,
    SOURCE_PORT_REGEX_PROBLEM,
    DESTINATION_PORT_NULL_PROBLEM,
    SOURCE_PORT_NULL_PROBLEM,
    DESTINATION_PORT_REGEX_PROBLEM,
    IDENTITY_NOT_FOUND,
    FIRSTNAME_NOT_FOUND,
    LASTNAME_NOT_FOUND,
    LONGITUDE_NULL_PROBLEM,
    LATITUDE_NULL_PROBLEM,
    NATIONAL_ID_NOT_FOUND,
}
