plugins {
    id 'application'
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'

}

group = 'org.shahin'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = 'org.shahin.Main'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'ch.qos.logback:logback-classic:1.5.18'
    implementation 'org.apache.spark:spark-sql_2.13:3.3.3'
}
shadowJar {
    archiveBaseName.set('analysis')
    zip64 true
    archiveVersion.set('')
    mergeServiceFiles()
    manifest {
        attributes 'Main-Class': 'org.shahin.Main'
    }
}

test {
    useJUnitPlatform()
}