// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: net_reord.proto
// Protobuf Java Version: 4.33.1

package org.shahin.protobuf;

@com.google.protobuf.Generated
public final class NetRecordProto extends com.google.protobuf.GeneratedFile {
  private NetRecordProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "NetRecordProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.NetRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>required string ipv4_src_addr = 2;</code>
     * @return Whether the ipv4SrcAddr field is set.
     */
    boolean hasIpv4SrcAddr();
    /**
     * <code>required string ipv4_src_addr = 2;</code>
     * @return The ipv4SrcAddr.
     */
    String getIpv4SrcAddr();
    /**
     * <code>required string ipv4_src_addr = 2;</code>
     * @return The bytes for ipv4SrcAddr.
     */
    com.google.protobuf.ByteString
        getIpv4SrcAddrBytes();

    /**
     * <code>required int32 l4_src_port = 3;</code>
     * @return Whether the l4SrcPort field is set.
     */
    boolean hasL4SrcPort();
    /**
     * <code>required int32 l4_src_port = 3;</code>
     * @return The l4SrcPort.
     */
    int getL4SrcPort();

    /**
     * <code>required string ipv4_dst_addr = 4;</code>
     * @return Whether the ipv4DstAddr field is set.
     */
    boolean hasIpv4DstAddr();
    /**
     * <code>required string ipv4_dst_addr = 4;</code>
     * @return The ipv4DstAddr.
     */
    String getIpv4DstAddr();
    /**
     * <code>required string ipv4_dst_addr = 4;</code>
     * @return The bytes for ipv4DstAddr.
     */
    com.google.protobuf.ByteString
        getIpv4DstAddrBytes();

    /**
     * <code>required int32 l4_dst_port = 5;</code>
     * @return Whether the l4DstPort field is set.
     */
    boolean hasL4DstPort();
    /**
     * <code>required int32 l4_dst_port = 5;</code>
     * @return The l4DstPort.
     */
    int getL4DstPort();

    /**
     * <code>required int32 in_bytes = 6;</code>
     * @return Whether the inBytes field is set.
     */
    boolean hasInBytes();
    /**
     * <code>required int32 in_bytes = 6;</code>
     * @return The inBytes.
     */
    int getInBytes();

    /**
     * <code>required int32 out_bytes = 7;</code>
     * @return Whether the outBytes field is set.
     */
    boolean hasOutBytes();
    /**
     * <code>required int32 out_bytes = 7;</code>
     * @return The outBytes.
     */
    int getOutBytes();

    /**
     * <code>required string sender_first_name = 8;</code>
     * @return Whether the senderFirstName field is set.
     */
    boolean hasSenderFirstName();
    /**
     * <code>required string sender_first_name = 8;</code>
     * @return The senderFirstName.
     */
    String getSenderFirstName();
    /**
     * <code>required string sender_first_name = 8;</code>
     * @return The bytes for senderFirstName.
     */
    com.google.protobuf.ByteString
        getSenderFirstNameBytes();

    /**
     * <code>required string sender_last_name = 9;</code>
     * @return Whether the senderLastName field is set.
     */
    boolean hasSenderLastName();
    /**
     * <code>required string sender_last_name = 9;</code>
     * @return The senderLastName.
     */
    String getSenderLastName();
    /**
     * <code>required string sender_last_name = 9;</code>
     * @return The bytes for senderLastName.
     */
    com.google.protobuf.ByteString
        getSenderLastNameBytes();

    /**
     * <code>required string sender_national_id = 10;</code>
     * @return Whether the senderNationalId field is set.
     */
    boolean hasSenderNationalId();
    /**
     * <code>required string sender_national_id = 10;</code>
     * @return The senderNationalId.
     */
    String getSenderNationalId();
    /**
     * <code>required string sender_national_id = 10;</code>
     * @return The bytes for senderNationalId.
     */
    com.google.protobuf.ByteString
        getSenderNationalIdBytes();

    /**
     * <code>required string sender_latitude = 11;</code>
     * @return Whether the senderLatitude field is set.
     */
    boolean hasSenderLatitude();
    /**
     * <code>required string sender_latitude = 11;</code>
     * @return The senderLatitude.
     */
    String getSenderLatitude();
    /**
     * <code>required string sender_latitude = 11;</code>
     * @return The bytes for senderLatitude.
     */
    com.google.protobuf.ByteString
        getSenderLatitudeBytes();

    /**
     * <code>required string sender_longitude = 12;</code>
     * @return Whether the senderLongitude field is set.
     */
    boolean hasSenderLongitude();
    /**
     * <code>required string sender_longitude = 12;</code>
     * @return The senderLongitude.
     */
    String getSenderLongitude();
    /**
     * <code>required string sender_longitude = 12;</code>
     * @return The bytes for senderLongitude.
     */
    com.google.protobuf.ByteString
        getSenderLongitudeBytes();
  }
  /**
   * Protobuf type {@code protobuf.NetRecord}
   */
  public static final class NetRecord extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.NetRecord)
      NetRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 1,
        /* suffix= */ "",
        "NetRecord");
    }
    // Use NetRecord.newBuilder() to construct.
    private NetRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NetRecord() {
      ipv4SrcAddr_ = "";
      ipv4DstAddr_ = "";
      senderFirstName_ = "";
      senderLastName_ = "";
      senderNationalId_ = "";
      senderLatitude_ = "";
      senderLongitude_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetRecordProto.internal_static_protobuf_NetRecord_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetRecordProto.internal_static_protobuf_NetRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetRecord.class, Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_ = 0L;
    /**
     * <code>required uint64 timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    @Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int IPV4_SRC_ADDR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object ipv4SrcAddr_ = "";
    /**
     * <code>required string ipv4_src_addr = 2;</code>
     * @return Whether the ipv4SrcAddr field is set.
     */
    @Override
    public boolean hasIpv4SrcAddr() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string ipv4_src_addr = 2;</code>
     * @return The ipv4SrcAddr.
     */
    @Override
    public String getIpv4SrcAddr() {
      Object ref = ipv4SrcAddr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipv4SrcAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ipv4_src_addr = 2;</code>
     * @return The bytes for ipv4SrcAddr.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpv4SrcAddrBytes() {
      Object ref = ipv4SrcAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ipv4SrcAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int L4_SRC_PORT_FIELD_NUMBER = 3;
    private int l4SrcPort_ = 0;
    /**
     * <code>required int32 l4_src_port = 3;</code>
     * @return Whether the l4SrcPort field is set.
     */
    @Override
    public boolean hasL4SrcPort() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 l4_src_port = 3;</code>
     * @return The l4SrcPort.
     */
    @Override
    public int getL4SrcPort() {
      return l4SrcPort_;
    }

    public static final int IPV4_DST_ADDR_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object ipv4DstAddr_ = "";
    /**
     * <code>required string ipv4_dst_addr = 4;</code>
     * @return Whether the ipv4DstAddr field is set.
     */
    @Override
    public boolean hasIpv4DstAddr() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string ipv4_dst_addr = 4;</code>
     * @return The ipv4DstAddr.
     */
    @Override
    public String getIpv4DstAddr() {
      Object ref = ipv4DstAddr_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipv4DstAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ipv4_dst_addr = 4;</code>
     * @return The bytes for ipv4DstAddr.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpv4DstAddrBytes() {
      Object ref = ipv4DstAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ipv4DstAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int L4_DST_PORT_FIELD_NUMBER = 5;
    private int l4DstPort_ = 0;
    /**
     * <code>required int32 l4_dst_port = 5;</code>
     * @return Whether the l4DstPort field is set.
     */
    @Override
    public boolean hasL4DstPort() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 l4_dst_port = 5;</code>
     * @return The l4DstPort.
     */
    @Override
    public int getL4DstPort() {
      return l4DstPort_;
    }

    public static final int IN_BYTES_FIELD_NUMBER = 6;
    private int inBytes_ = 0;
    /**
     * <code>required int32 in_bytes = 6;</code>
     * @return Whether the inBytes field is set.
     */
    @Override
    public boolean hasInBytes() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 in_bytes = 6;</code>
     * @return The inBytes.
     */
    @Override
    public int getInBytes() {
      return inBytes_;
    }

    public static final int OUT_BYTES_FIELD_NUMBER = 7;
    private int outBytes_ = 0;
    /**
     * <code>required int32 out_bytes = 7;</code>
     * @return Whether the outBytes field is set.
     */
    @Override
    public boolean hasOutBytes() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required int32 out_bytes = 7;</code>
     * @return The outBytes.
     */
    @Override
    public int getOutBytes() {
      return outBytes_;
    }

    public static final int SENDER_FIRST_NAME_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile Object senderFirstName_ = "";
    /**
     * <code>required string sender_first_name = 8;</code>
     * @return Whether the senderFirstName field is set.
     */
    @Override
    public boolean hasSenderFirstName() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>required string sender_first_name = 8;</code>
     * @return The senderFirstName.
     */
    @Override
    public String getSenderFirstName() {
      Object ref = senderFirstName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderFirstName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender_first_name = 8;</code>
     * @return The bytes for senderFirstName.
     */
    @Override
    public com.google.protobuf.ByteString
        getSenderFirstNameBytes() {
      Object ref = senderFirstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderFirstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_LAST_NAME_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile Object senderLastName_ = "";
    /**
     * <code>required string sender_last_name = 9;</code>
     * @return Whether the senderLastName field is set.
     */
    @Override
    public boolean hasSenderLastName() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>required string sender_last_name = 9;</code>
     * @return The senderLastName.
     */
    @Override
    public String getSenderLastName() {
      Object ref = senderLastName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderLastName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender_last_name = 9;</code>
     * @return The bytes for senderLastName.
     */
    @Override
    public com.google.protobuf.ByteString
        getSenderLastNameBytes() {
      Object ref = senderLastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderLastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_NATIONAL_ID_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private volatile Object senderNationalId_ = "";
    /**
     * <code>required string sender_national_id = 10;</code>
     * @return Whether the senderNationalId field is set.
     */
    @Override
    public boolean hasSenderNationalId() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>required string sender_national_id = 10;</code>
     * @return The senderNationalId.
     */
    @Override
    public String getSenderNationalId() {
      Object ref = senderNationalId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderNationalId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender_national_id = 10;</code>
     * @return The bytes for senderNationalId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSenderNationalIdBytes() {
      Object ref = senderNationalId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderNationalId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_LATITUDE_FIELD_NUMBER = 11;
    @SuppressWarnings("serial")
    private volatile Object senderLatitude_ = "";
    /**
     * <code>required string sender_latitude = 11;</code>
     * @return Whether the senderLatitude field is set.
     */
    @Override
    public boolean hasSenderLatitude() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>required string sender_latitude = 11;</code>
     * @return The senderLatitude.
     */
    @Override
    public String getSenderLatitude() {
      Object ref = senderLatitude_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderLatitude_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender_latitude = 11;</code>
     * @return The bytes for senderLatitude.
     */
    @Override
    public com.google.protobuf.ByteString
        getSenderLatitudeBytes() {
      Object ref = senderLatitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderLatitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_LONGITUDE_FIELD_NUMBER = 12;
    @SuppressWarnings("serial")
    private volatile Object senderLongitude_ = "";
    /**
     * <code>required string sender_longitude = 12;</code>
     * @return Whether the senderLongitude field is set.
     */
    @Override
    public boolean hasSenderLongitude() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>required string sender_longitude = 12;</code>
     * @return The senderLongitude.
     */
    @Override
    public String getSenderLongitude() {
      Object ref = senderLongitude_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderLongitude_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sender_longitude = 12;</code>
     * @return The bytes for senderLongitude.
     */
    @Override
    public com.google.protobuf.ByteString
        getSenderLongitudeBytes() {
      Object ref = senderLongitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        senderLongitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpv4SrcAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasL4SrcPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpv4DstAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasL4DstPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOutBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderFirstName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderLastName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderNationalId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, ipv4SrcAddr_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, l4SrcPort_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, ipv4DstAddr_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, l4DstPort_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, inBytes_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(7, outBytes_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, senderFirstName_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, senderLastName_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, senderNationalId_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 11, senderLatitude_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 12, senderLongitude_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, ipv4SrcAddr_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, l4SrcPort_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, ipv4DstAddr_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, l4DstPort_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, inBytes_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, outBytes_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(8, senderFirstName_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(9, senderLastName_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(10, senderNationalId_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(11, senderLatitude_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(12, senderLongitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NetRecord)) {
        return super.equals(obj);
      }
      NetRecord other = (NetRecord) obj;

      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (getTimestamp()
            != other.getTimestamp()) return false;
      }
      if (hasIpv4SrcAddr() != other.hasIpv4SrcAddr()) return false;
      if (hasIpv4SrcAddr()) {
        if (!getIpv4SrcAddr()
            .equals(other.getIpv4SrcAddr())) return false;
      }
      if (hasL4SrcPort() != other.hasL4SrcPort()) return false;
      if (hasL4SrcPort()) {
        if (getL4SrcPort()
            != other.getL4SrcPort()) return false;
      }
      if (hasIpv4DstAddr() != other.hasIpv4DstAddr()) return false;
      if (hasIpv4DstAddr()) {
        if (!getIpv4DstAddr()
            .equals(other.getIpv4DstAddr())) return false;
      }
      if (hasL4DstPort() != other.hasL4DstPort()) return false;
      if (hasL4DstPort()) {
        if (getL4DstPort()
            != other.getL4DstPort()) return false;
      }
      if (hasInBytes() != other.hasInBytes()) return false;
      if (hasInBytes()) {
        if (getInBytes()
            != other.getInBytes()) return false;
      }
      if (hasOutBytes() != other.hasOutBytes()) return false;
      if (hasOutBytes()) {
        if (getOutBytes()
            != other.getOutBytes()) return false;
      }
      if (hasSenderFirstName() != other.hasSenderFirstName()) return false;
      if (hasSenderFirstName()) {
        if (!getSenderFirstName()
            .equals(other.getSenderFirstName())) return false;
      }
      if (hasSenderLastName() != other.hasSenderLastName()) return false;
      if (hasSenderLastName()) {
        if (!getSenderLastName()
            .equals(other.getSenderLastName())) return false;
      }
      if (hasSenderNationalId() != other.hasSenderNationalId()) return false;
      if (hasSenderNationalId()) {
        if (!getSenderNationalId()
            .equals(other.getSenderNationalId())) return false;
      }
      if (hasSenderLatitude() != other.hasSenderLatitude()) return false;
      if (hasSenderLatitude()) {
        if (!getSenderLatitude()
            .equals(other.getSenderLatitude())) return false;
      }
      if (hasSenderLongitude() != other.hasSenderLongitude()) return false;
      if (hasSenderLongitude()) {
        if (!getSenderLongitude()
            .equals(other.getSenderLongitude())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
      }
      if (hasIpv4SrcAddr()) {
        hash = (37 * hash) + IPV4_SRC_ADDR_FIELD_NUMBER;
        hash = (53 * hash) + getIpv4SrcAddr().hashCode();
      }
      if (hasL4SrcPort()) {
        hash = (37 * hash) + L4_SRC_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getL4SrcPort();
      }
      if (hasIpv4DstAddr()) {
        hash = (37 * hash) + IPV4_DST_ADDR_FIELD_NUMBER;
        hash = (53 * hash) + getIpv4DstAddr().hashCode();
      }
      if (hasL4DstPort()) {
        hash = (37 * hash) + L4_DST_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getL4DstPort();
      }
      if (hasInBytes()) {
        hash = (37 * hash) + IN_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getInBytes();
      }
      if (hasOutBytes()) {
        hash = (37 * hash) + OUT_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getOutBytes();
      }
      if (hasSenderFirstName()) {
        hash = (37 * hash) + SENDER_FIRST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSenderFirstName().hashCode();
      }
      if (hasSenderLastName()) {
        hash = (37 * hash) + SENDER_LAST_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSenderLastName().hashCode();
      }
      if (hasSenderNationalId()) {
        hash = (37 * hash) + SENDER_NATIONAL_ID_FIELD_NUMBER;
        hash = (53 * hash) + getSenderNationalId().hashCode();
      }
      if (hasSenderLatitude()) {
        hash = (37 * hash) + SENDER_LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getSenderLatitude().hashCode();
      }
      if (hasSenderLongitude()) {
        hash = (37 * hash) + SENDER_LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + getSenderLongitude().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NetRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static NetRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static NetRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static NetRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NetRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static NetRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NetRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.NetRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.NetRecord)
        NetRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetRecordProto.internal_static_protobuf_NetRecord_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetRecordProto.internal_static_protobuf_NetRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetRecord.class, Builder.class);
      }

      // Construct using org.shahin.protobuf.NetRecordProto.NetRecord.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = 0L;
        ipv4SrcAddr_ = "";
        l4SrcPort_ = 0;
        ipv4DstAddr_ = "";
        l4DstPort_ = 0;
        inBytes_ = 0;
        outBytes_ = 0;
        senderFirstName_ = "";
        senderLastName_ = "";
        senderNationalId_ = "";
        senderLatitude_ = "";
        senderLongitude_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetRecordProto.internal_static_protobuf_NetRecord_descriptor;
      }

      @Override
      public NetRecord getDefaultInstanceForType() {
        return NetRecord.getDefaultInstance();
      }

      @Override
      public NetRecord build() {
        NetRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NetRecord buildPartial() {
        NetRecord result = new NetRecord(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(NetRecord result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.ipv4SrcAddr_ = ipv4SrcAddr_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.l4SrcPort_ = l4SrcPort_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ipv4DstAddr_ = ipv4DstAddr_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.l4DstPort_ = l4DstPort_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.inBytes_ = inBytes_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.outBytes_ = outBytes_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.senderFirstName_ = senderFirstName_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.senderLastName_ = senderLastName_;
          to_bitField0_ |= 0x00000100;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.senderNationalId_ = senderNationalId_;
          to_bitField0_ |= 0x00000200;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.senderLatitude_ = senderLatitude_;
          to_bitField0_ |= 0x00000400;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.senderLongitude_ = senderLongitude_;
          to_bitField0_ |= 0x00000800;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetRecord) {
          return mergeFrom((NetRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetRecord other) {
        if (other == NetRecord.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasIpv4SrcAddr()) {
          ipv4SrcAddr_ = other.ipv4SrcAddr_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasL4SrcPort()) {
          setL4SrcPort(other.getL4SrcPort());
        }
        if (other.hasIpv4DstAddr()) {
          ipv4DstAddr_ = other.ipv4DstAddr_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasL4DstPort()) {
          setL4DstPort(other.getL4DstPort());
        }
        if (other.hasInBytes()) {
          setInBytes(other.getInBytes());
        }
        if (other.hasOutBytes()) {
          setOutBytes(other.getOutBytes());
        }
        if (other.hasSenderFirstName()) {
          senderFirstName_ = other.senderFirstName_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        if (other.hasSenderLastName()) {
          senderLastName_ = other.senderLastName_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        if (other.hasSenderNationalId()) {
          senderNationalId_ = other.senderNationalId_;
          bitField0_ |= 0x00000200;
          onChanged();
        }
        if (other.hasSenderLatitude()) {
          senderLatitude_ = other.senderLatitude_;
          bitField0_ |= 0x00000400;
          onChanged();
        }
        if (other.hasSenderLongitude()) {
          senderLongitude_ = other.senderLongitude_;
          bitField0_ |= 0x00000800;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          return false;
        }
        if (!hasIpv4SrcAddr()) {
          return false;
        }
        if (!hasL4SrcPort()) {
          return false;
        }
        if (!hasIpv4DstAddr()) {
          return false;
        }
        if (!hasL4DstPort()) {
          return false;
        }
        if (!hasInBytes()) {
          return false;
        }
        if (!hasOutBytes()) {
          return false;
        }
        if (!hasSenderFirstName()) {
          return false;
        }
        if (!hasSenderLastName()) {
          return false;
        }
        if (!hasSenderNationalId()) {
          return false;
        }
        if (!hasSenderLatitude()) {
          return false;
        }
        if (!hasSenderLongitude()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestamp_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                ipv4SrcAddr_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                l4SrcPort_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                ipv4DstAddr_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                l4DstPort_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                inBytes_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                outBytes_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                senderFirstName_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                senderLastName_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                senderNationalId_ = input.readBytes();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              case 90: {
                senderLatitude_ = input.readBytes();
                bitField0_ |= 0x00000400;
                break;
              } // case 90
              case 98: {
                senderLongitude_ = input.readBytes();
                bitField0_ |= 0x00000800;
                break;
              } // case 98
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 1;</code>
       * @return Whether the timestamp field is set.
       */
      @Override
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required uint64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object ipv4SrcAddr_ = "";
      /**
       * <code>required string ipv4_src_addr = 2;</code>
       * @return Whether the ipv4SrcAddr field is set.
       */
      public boolean hasIpv4SrcAddr() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string ipv4_src_addr = 2;</code>
       * @return The ipv4SrcAddr.
       */
      public String getIpv4SrcAddr() {
        Object ref = ipv4SrcAddr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipv4SrcAddr_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ipv4_src_addr = 2;</code>
       * @return The bytes for ipv4SrcAddr.
       */
      public com.google.protobuf.ByteString
          getIpv4SrcAddrBytes() {
        Object ref = ipv4SrcAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ipv4SrcAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ipv4_src_addr = 2;</code>
       * @param value The ipv4SrcAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpv4SrcAddr(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ipv4SrcAddr_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_src_addr = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpv4SrcAddr() {
        ipv4SrcAddr_ = getDefaultInstance().getIpv4SrcAddr();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_src_addr = 2;</code>
       * @param value The bytes for ipv4SrcAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpv4SrcAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ipv4SrcAddr_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int l4SrcPort_ ;
      /**
       * <code>required int32 l4_src_port = 3;</code>
       * @return Whether the l4SrcPort field is set.
       */
      @Override
      public boolean hasL4SrcPort() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 l4_src_port = 3;</code>
       * @return The l4SrcPort.
       */
      @Override
      public int getL4SrcPort() {
        return l4SrcPort_;
      }
      /**
       * <code>required int32 l4_src_port = 3;</code>
       * @param value The l4SrcPort to set.
       * @return This builder for chaining.
       */
      public Builder setL4SrcPort(int value) {

        l4SrcPort_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 l4_src_port = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearL4SrcPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        l4SrcPort_ = 0;
        onChanged();
        return this;
      }

      private Object ipv4DstAddr_ = "";
      /**
       * <code>required string ipv4_dst_addr = 4;</code>
       * @return Whether the ipv4DstAddr field is set.
       */
      public boolean hasIpv4DstAddr() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string ipv4_dst_addr = 4;</code>
       * @return The ipv4DstAddr.
       */
      public String getIpv4DstAddr() {
        Object ref = ipv4DstAddr_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipv4DstAddr_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ipv4_dst_addr = 4;</code>
       * @return The bytes for ipv4DstAddr.
       */
      public com.google.protobuf.ByteString
          getIpv4DstAddrBytes() {
        Object ref = ipv4DstAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ipv4DstAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ipv4_dst_addr = 4;</code>
       * @param value The ipv4DstAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpv4DstAddr(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ipv4DstAddr_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_dst_addr = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpv4DstAddr() {
        ipv4DstAddr_ = getDefaultInstance().getIpv4DstAddr();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_dst_addr = 4;</code>
       * @param value The bytes for ipv4DstAddr to set.
       * @return This builder for chaining.
       */
      public Builder setIpv4DstAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ipv4DstAddr_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int l4DstPort_ ;
      /**
       * <code>required int32 l4_dst_port = 5;</code>
       * @return Whether the l4DstPort field is set.
       */
      @Override
      public boolean hasL4DstPort() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 l4_dst_port = 5;</code>
       * @return The l4DstPort.
       */
      @Override
      public int getL4DstPort() {
        return l4DstPort_;
      }
      /**
       * <code>required int32 l4_dst_port = 5;</code>
       * @param value The l4DstPort to set.
       * @return This builder for chaining.
       */
      public Builder setL4DstPort(int value) {

        l4DstPort_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 l4_dst_port = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearL4DstPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        l4DstPort_ = 0;
        onChanged();
        return this;
      }

      private int inBytes_ ;
      /**
       * <code>required int32 in_bytes = 6;</code>
       * @return Whether the inBytes field is set.
       */
      @Override
      public boolean hasInBytes() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int32 in_bytes = 6;</code>
       * @return The inBytes.
       */
      @Override
      public int getInBytes() {
        return inBytes_;
      }
      /**
       * <code>required int32 in_bytes = 6;</code>
       * @param value The inBytes to set.
       * @return This builder for chaining.
       */
      public Builder setInBytes(int value) {

        inBytes_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 in_bytes = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearInBytes() {
        bitField0_ = (bitField0_ & ~0x00000020);
        inBytes_ = 0;
        onChanged();
        return this;
      }

      private int outBytes_ ;
      /**
       * <code>required int32 out_bytes = 7;</code>
       * @return Whether the outBytes field is set.
       */
      @Override
      public boolean hasOutBytes() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required int32 out_bytes = 7;</code>
       * @return The outBytes.
       */
      @Override
      public int getOutBytes() {
        return outBytes_;
      }
      /**
       * <code>required int32 out_bytes = 7;</code>
       * @param value The outBytes to set.
       * @return This builder for chaining.
       */
      public Builder setOutBytes(int value) {

        outBytes_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 out_bytes = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearOutBytes() {
        bitField0_ = (bitField0_ & ~0x00000040);
        outBytes_ = 0;
        onChanged();
        return this;
      }

      private Object senderFirstName_ = "";
      /**
       * <code>required string sender_first_name = 8;</code>
       * @return Whether the senderFirstName field is set.
       */
      public boolean hasSenderFirstName() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>required string sender_first_name = 8;</code>
       * @return The senderFirstName.
       */
      public String getSenderFirstName() {
        Object ref = senderFirstName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderFirstName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sender_first_name = 8;</code>
       * @return The bytes for senderFirstName.
       */
      public com.google.protobuf.ByteString
          getSenderFirstNameBytes() {
        Object ref = senderFirstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderFirstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender_first_name = 8;</code>
       * @param value The senderFirstName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderFirstName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        senderFirstName_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_first_name = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderFirstName() {
        senderFirstName_ = getDefaultInstance().getSenderFirstName();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_first_name = 8;</code>
       * @param value The bytes for senderFirstName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        senderFirstName_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private Object senderLastName_ = "";
      /**
       * <code>required string sender_last_name = 9;</code>
       * @return Whether the senderLastName field is set.
       */
      public boolean hasSenderLastName() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>required string sender_last_name = 9;</code>
       * @return The senderLastName.
       */
      public String getSenderLastName() {
        Object ref = senderLastName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderLastName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sender_last_name = 9;</code>
       * @return The bytes for senderLastName.
       */
      public com.google.protobuf.ByteString
          getSenderLastNameBytes() {
        Object ref = senderLastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderLastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender_last_name = 9;</code>
       * @param value The senderLastName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderLastName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        senderLastName_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_last_name = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderLastName() {
        senderLastName_ = getDefaultInstance().getSenderLastName();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_last_name = 9;</code>
       * @param value The bytes for senderLastName to set.
       * @return This builder for chaining.
       */
      public Builder setSenderLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        senderLastName_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private Object senderNationalId_ = "";
      /**
       * <code>required string sender_national_id = 10;</code>
       * @return Whether the senderNationalId field is set.
       */
      public boolean hasSenderNationalId() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>required string sender_national_id = 10;</code>
       * @return The senderNationalId.
       */
      public String getSenderNationalId() {
        Object ref = senderNationalId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderNationalId_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sender_national_id = 10;</code>
       * @return The bytes for senderNationalId.
       */
      public com.google.protobuf.ByteString
          getSenderNationalIdBytes() {
        Object ref = senderNationalId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderNationalId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender_national_id = 10;</code>
       * @param value The senderNationalId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNationalId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        senderNationalId_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_national_id = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderNationalId() {
        senderNationalId_ = getDefaultInstance().getSenderNationalId();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_national_id = 10;</code>
       * @param value The bytes for senderNationalId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderNationalIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        senderNationalId_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private Object senderLatitude_ = "";
      /**
       * <code>required string sender_latitude = 11;</code>
       * @return Whether the senderLatitude field is set.
       */
      public boolean hasSenderLatitude() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>required string sender_latitude = 11;</code>
       * @return The senderLatitude.
       */
      public String getSenderLatitude() {
        Object ref = senderLatitude_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderLatitude_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sender_latitude = 11;</code>
       * @return The bytes for senderLatitude.
       */
      public com.google.protobuf.ByteString
          getSenderLatitudeBytes() {
        Object ref = senderLatitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderLatitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender_latitude = 11;</code>
       * @param value The senderLatitude to set.
       * @return This builder for chaining.
       */
      public Builder setSenderLatitude(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        senderLatitude_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_latitude = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderLatitude() {
        senderLatitude_ = getDefaultInstance().getSenderLatitude();
        bitField0_ = (bitField0_ & ~0x00000400);
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_latitude = 11;</code>
       * @param value The bytes for senderLatitude to set.
       * @return This builder for chaining.
       */
      public Builder setSenderLatitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        senderLatitude_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }

      private Object senderLongitude_ = "";
      /**
       * <code>required string sender_longitude = 12;</code>
       * @return Whether the senderLongitude field is set.
       */
      public boolean hasSenderLongitude() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>required string sender_longitude = 12;</code>
       * @return The senderLongitude.
       */
      public String getSenderLongitude() {
        Object ref = senderLongitude_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderLongitude_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sender_longitude = 12;</code>
       * @return The bytes for senderLongitude.
       */
      public com.google.protobuf.ByteString
          getSenderLongitudeBytes() {
        Object ref = senderLongitude_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          senderLongitude_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sender_longitude = 12;</code>
       * @param value The senderLongitude to set.
       * @return This builder for chaining.
       */
      public Builder setSenderLongitude(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        senderLongitude_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_longitude = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderLongitude() {
        senderLongitude_ = getDefaultInstance().getSenderLongitude();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
        return this;
      }
      /**
       * <code>required string sender_longitude = 12;</code>
       * @param value The bytes for senderLongitude to set.
       * @return This builder for chaining.
       */
      public Builder setSenderLongitudeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        senderLongitude_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.NetRecord)
    }

    // @@protoc_insertion_point(class_scope:protobuf.NetRecord)
    private static final NetRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NetRecord();
    }

    public static NetRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetRecord>
        PARSER = new com.google.protobuf.AbstractParser<NetRecord>() {
      @Override
      public NetRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NetRecord> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NetRecord> getParserForType() {
      return PARSER;
    }

    @Override
    public NetRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_NetRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_NetRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017net_reord.proto\022\010protobuf\"\237\002\n\tNetRecor" +
      "d\022\021\n\ttimestamp\030\001 \002(\004\022\025\n\ripv4_src_addr\030\002 " +
      "\002(\t\022\023\n\013l4_src_port\030\003 \002(\005\022\025\n\ripv4_dst_add" +
      "r\030\004 \002(\t\022\023\n\013l4_dst_port\030\005 \002(\005\022\020\n\010in_bytes" +
      "\030\006 \002(\005\022\021\n\tout_bytes\030\007 \002(\005\022\031\n\021sender_firs" +
      "t_name\030\010 \002(\t\022\030\n\020sender_last_name\030\t \002(\t\022\032" +
      "\n\022sender_national_id\030\n \002(\t\022\027\n\017sender_lat" +
      "itude\030\013 \002(\t\022\030\n\020sender_longitude\030\014 \002(\tB%\n" +
      "\023org.shahin.protobufB\016NetRecordProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_NetRecord_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_protobuf_NetRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_NetRecord_descriptor,
        new String[] { "Timestamp", "Ipv4SrcAddr", "L4SrcPort", "Ipv4DstAddr", "L4DstPort", "InBytes", "OutBytes", "SenderFirstName", "SenderLastName", "SenderNationalId", "SenderLatitude", "SenderLongitude", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
