// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/net_reord.proto

package org.shahin.protobuf;

public final class NetRecordProto {
  private NetRecordProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NetRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.NetRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string date = 1;</code>
     */
    boolean hasDate();
    /**
     * <code>required string date = 1;</code>
     */
    java.lang.String getDate();
    /**
     * <code>required string date = 1;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>required int32 hour = 2;</code>
     */
    boolean hasHour();
    /**
     * <code>required int32 hour = 2;</code>
     */
    int getHour();

    /**
     * <code>required int32 minute = 3;</code>
     */
    boolean hasMinute();
    /**
     * <code>required int32 minute = 3;</code>
     */
    int getMinute();

    /**
     * <code>required string ipv4_src_addr = 4;</code>
     */
    boolean hasIpv4SrcAddr();
    /**
     * <code>required string ipv4_src_addr = 4;</code>
     */
    java.lang.String getIpv4SrcAddr();
    /**
     * <code>required string ipv4_src_addr = 4;</code>
     */
    com.google.protobuf.ByteString
        getIpv4SrcAddrBytes();

    /**
     * <code>required int32 l4_src_port = 5;</code>
     */
    boolean hasL4SrcPort();
    /**
     * <code>required int32 l4_src_port = 5;</code>
     */
    int getL4SrcPort();

    /**
     * <code>required string ipv4_dst_addr = 6;</code>
     */
    boolean hasIpv4DstAddr();
    /**
     * <code>required string ipv4_dst_addr = 6;</code>
     */
    java.lang.String getIpv4DstAddr();
    /**
     * <code>required string ipv4_dst_addr = 6;</code>
     */
    com.google.protobuf.ByteString
        getIpv4DstAddrBytes();

    /**
     * <code>required int32 l4_dst_port = 7;</code>
     */
    boolean hasL4DstPort();
    /**
     * <code>required int32 l4_dst_port = 7;</code>
     */
    int getL4DstPort();

    /**
     * <code>required int32 in_bytes = 8;</code>
     */
    boolean hasInBytes();
    /**
     * <code>required int32 in_bytes = 8;</code>
     */
    int getInBytes();

    /**
     * <code>required int32 out_bytes = 9;</code>
     */
    boolean hasOutBytes();
    /**
     * <code>required int32 out_bytes = 9;</code>
     */
    int getOutBytes();
  }
  /**
   * Protobuf type {@code protobuf.NetRecord}
   */
  public  static final class NetRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.NetRecord)
      NetRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NetRecord.newBuilder() to construct.
    private NetRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetRecord() {
      date_ = "";
      hour_ = 0;
      minute_ = 0;
      ipv4SrcAddr_ = "";
      l4SrcPort_ = 0;
      ipv4DstAddr_ = "";
      l4DstPort_ = 0;
      inBytes_ = 0;
      outBytes_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NetRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              date_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hour_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              minute_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              ipv4SrcAddr_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              l4SrcPort_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              ipv4DstAddr_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              l4DstPort_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              inBytes_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              outBytes_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.shahin.protobuf.NetRecordProto.internal_static_protobuf_NetRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.shahin.protobuf.NetRecordProto.internal_static_protobuf_NetRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.shahin.protobuf.NetRecordProto.NetRecord.class, org.shahin.protobuf.NetRecordProto.NetRecord.Builder.class);
    }

    private int bitField0_;
    public static final int DATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object date_;
    /**
     * <code>required string date = 1;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string date = 1;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOUR_FIELD_NUMBER = 2;
    private int hour_;
    /**
     * <code>required int32 hour = 2;</code>
     */
    public boolean hasHour() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 hour = 2;</code>
     */
    public int getHour() {
      return hour_;
    }

    public static final int MINUTE_FIELD_NUMBER = 3;
    private int minute_;
    /**
     * <code>required int32 minute = 3;</code>
     */
    public boolean hasMinute() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 minute = 3;</code>
     */
    public int getMinute() {
      return minute_;
    }

    public static final int IPV4_SRC_ADDR_FIELD_NUMBER = 4;
    private volatile java.lang.Object ipv4SrcAddr_;
    /**
     * <code>required string ipv4_src_addr = 4;</code>
     */
    public boolean hasIpv4SrcAddr() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string ipv4_src_addr = 4;</code>
     */
    public java.lang.String getIpv4SrcAddr() {
      java.lang.Object ref = ipv4SrcAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipv4SrcAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ipv4_src_addr = 4;</code>
     */
    public com.google.protobuf.ByteString
        getIpv4SrcAddrBytes() {
      java.lang.Object ref = ipv4SrcAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv4SrcAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int L4_SRC_PORT_FIELD_NUMBER = 5;
    private int l4SrcPort_;
    /**
     * <code>required int32 l4_src_port = 5;</code>
     */
    public boolean hasL4SrcPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 l4_src_port = 5;</code>
     */
    public int getL4SrcPort() {
      return l4SrcPort_;
    }

    public static final int IPV4_DST_ADDR_FIELD_NUMBER = 6;
    private volatile java.lang.Object ipv4DstAddr_;
    /**
     * <code>required string ipv4_dst_addr = 6;</code>
     */
    public boolean hasIpv4DstAddr() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string ipv4_dst_addr = 6;</code>
     */
    public java.lang.String getIpv4DstAddr() {
      java.lang.Object ref = ipv4DstAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipv4DstAddr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ipv4_dst_addr = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIpv4DstAddrBytes() {
      java.lang.Object ref = ipv4DstAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipv4DstAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int L4_DST_PORT_FIELD_NUMBER = 7;
    private int l4DstPort_;
    /**
     * <code>required int32 l4_dst_port = 7;</code>
     */
    public boolean hasL4DstPort() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 l4_dst_port = 7;</code>
     */
    public int getL4DstPort() {
      return l4DstPort_;
    }

    public static final int IN_BYTES_FIELD_NUMBER = 8;
    private int inBytes_;
    /**
     * <code>required int32 in_bytes = 8;</code>
     */
    public boolean hasInBytes() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 in_bytes = 8;</code>
     */
    public int getInBytes() {
      return inBytes_;
    }

    public static final int OUT_BYTES_FIELD_NUMBER = 9;
    private int outBytes_;
    /**
     * <code>required int32 out_bytes = 9;</code>
     */
    public boolean hasOutBytes() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 out_bytes = 9;</code>
     */
    public int getOutBytes() {
      return outBytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHour()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMinute()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpv4SrcAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasL4SrcPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpv4DstAddr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasL4DstPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOutBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, hour_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, minute_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ipv4SrcAddr_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, l4SrcPort_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ipv4DstAddr_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, l4DstPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, inBytes_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, outBytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, hour_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, minute_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ipv4SrcAddr_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, l4SrcPort_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ipv4DstAddr_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, l4DstPort_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, inBytes_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, outBytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.shahin.protobuf.NetRecordProto.NetRecord)) {
        return super.equals(obj);
      }
      org.shahin.protobuf.NetRecordProto.NetRecord other = (org.shahin.protobuf.NetRecordProto.NetRecord) obj;

      boolean result = true;
      result = result && (hasDate() == other.hasDate());
      if (hasDate()) {
        result = result && getDate()
            .equals(other.getDate());
      }
      result = result && (hasHour() == other.hasHour());
      if (hasHour()) {
        result = result && (getHour()
            == other.getHour());
      }
      result = result && (hasMinute() == other.hasMinute());
      if (hasMinute()) {
        result = result && (getMinute()
            == other.getMinute());
      }
      result = result && (hasIpv4SrcAddr() == other.hasIpv4SrcAddr());
      if (hasIpv4SrcAddr()) {
        result = result && getIpv4SrcAddr()
            .equals(other.getIpv4SrcAddr());
      }
      result = result && (hasL4SrcPort() == other.hasL4SrcPort());
      if (hasL4SrcPort()) {
        result = result && (getL4SrcPort()
            == other.getL4SrcPort());
      }
      result = result && (hasIpv4DstAddr() == other.hasIpv4DstAddr());
      if (hasIpv4DstAddr()) {
        result = result && getIpv4DstAddr()
            .equals(other.getIpv4DstAddr());
      }
      result = result && (hasL4DstPort() == other.hasL4DstPort());
      if (hasL4DstPort()) {
        result = result && (getL4DstPort()
            == other.getL4DstPort());
      }
      result = result && (hasInBytes() == other.hasInBytes());
      if (hasInBytes()) {
        result = result && (getInBytes()
            == other.getInBytes());
      }
      result = result && (hasOutBytes() == other.hasOutBytes());
      if (hasOutBytes()) {
        result = result && (getOutBytes()
            == other.getOutBytes());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (hasHour()) {
        hash = (37 * hash) + HOUR_FIELD_NUMBER;
        hash = (53 * hash) + getHour();
      }
      if (hasMinute()) {
        hash = (37 * hash) + MINUTE_FIELD_NUMBER;
        hash = (53 * hash) + getMinute();
      }
      if (hasIpv4SrcAddr()) {
        hash = (37 * hash) + IPV4_SRC_ADDR_FIELD_NUMBER;
        hash = (53 * hash) + getIpv4SrcAddr().hashCode();
      }
      if (hasL4SrcPort()) {
        hash = (37 * hash) + L4_SRC_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getL4SrcPort();
      }
      if (hasIpv4DstAddr()) {
        hash = (37 * hash) + IPV4_DST_ADDR_FIELD_NUMBER;
        hash = (53 * hash) + getIpv4DstAddr().hashCode();
      }
      if (hasL4DstPort()) {
        hash = (37 * hash) + L4_DST_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getL4DstPort();
      }
      if (hasInBytes()) {
        hash = (37 * hash) + IN_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getInBytes();
      }
      if (hasOutBytes()) {
        hash = (37 * hash) + OUT_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getOutBytes();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.shahin.protobuf.NetRecordProto.NetRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.shahin.protobuf.NetRecordProto.NetRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.NetRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.NetRecord)
        org.shahin.protobuf.NetRecordProto.NetRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.shahin.protobuf.NetRecordProto.internal_static_protobuf_NetRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.shahin.protobuf.NetRecordProto.internal_static_protobuf_NetRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.shahin.protobuf.NetRecordProto.NetRecord.class, org.shahin.protobuf.NetRecordProto.NetRecord.Builder.class);
      }

      // Construct using org.shahin.protobuf.NetRecordProto.NetRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        hour_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        minute_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ipv4SrcAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        l4SrcPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        ipv4DstAddr_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        l4DstPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        inBytes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        outBytes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.shahin.protobuf.NetRecordProto.internal_static_protobuf_NetRecord_descriptor;
      }

      @java.lang.Override
      public org.shahin.protobuf.NetRecordProto.NetRecord getDefaultInstanceForType() {
        return org.shahin.protobuf.NetRecordProto.NetRecord.getDefaultInstance();
      }

      @java.lang.Override
      public org.shahin.protobuf.NetRecordProto.NetRecord build() {
        org.shahin.protobuf.NetRecordProto.NetRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.shahin.protobuf.NetRecordProto.NetRecord buildPartial() {
        org.shahin.protobuf.NetRecordProto.NetRecord result = new org.shahin.protobuf.NetRecordProto.NetRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hour_ = hour_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.minute_ = minute_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ipv4SrcAddr_ = ipv4SrcAddr_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.l4SrcPort_ = l4SrcPort_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ipv4DstAddr_ = ipv4DstAddr_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.l4DstPort_ = l4DstPort_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.inBytes_ = inBytes_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.outBytes_ = outBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.shahin.protobuf.NetRecordProto.NetRecord) {
          return mergeFrom((org.shahin.protobuf.NetRecordProto.NetRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.shahin.protobuf.NetRecordProto.NetRecord other) {
        if (other == org.shahin.protobuf.NetRecordProto.NetRecord.getDefaultInstance()) return this;
        if (other.hasDate()) {
          bitField0_ |= 0x00000001;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasHour()) {
          setHour(other.getHour());
        }
        if (other.hasMinute()) {
          setMinute(other.getMinute());
        }
        if (other.hasIpv4SrcAddr()) {
          bitField0_ |= 0x00000008;
          ipv4SrcAddr_ = other.ipv4SrcAddr_;
          onChanged();
        }
        if (other.hasL4SrcPort()) {
          setL4SrcPort(other.getL4SrcPort());
        }
        if (other.hasIpv4DstAddr()) {
          bitField0_ |= 0x00000020;
          ipv4DstAddr_ = other.ipv4DstAddr_;
          onChanged();
        }
        if (other.hasL4DstPort()) {
          setL4DstPort(other.getL4DstPort());
        }
        if (other.hasInBytes()) {
          setInBytes(other.getInBytes());
        }
        if (other.hasOutBytes()) {
          setOutBytes(other.getOutBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDate()) {
          return false;
        }
        if (!hasHour()) {
          return false;
        }
        if (!hasMinute()) {
          return false;
        }
        if (!hasIpv4SrcAddr()) {
          return false;
        }
        if (!hasL4SrcPort()) {
          return false;
        }
        if (!hasIpv4DstAddr()) {
          return false;
        }
        if (!hasL4DstPort()) {
          return false;
        }
        if (!hasInBytes()) {
          return false;
        }
        if (!hasOutBytes()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.shahin.protobuf.NetRecordProto.NetRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.shahin.protobuf.NetRecordProto.NetRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object date_ = "";
      /**
       * <code>required string date = 1;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string date = 1;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string date = 1;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string date = 1;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }

      private int hour_ ;
      /**
       * <code>required int32 hour = 2;</code>
       */
      public boolean hasHour() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 hour = 2;</code>
       */
      public int getHour() {
        return hour_;
      }
      /**
       * <code>required int32 hour = 2;</code>
       */
      public Builder setHour(int value) {
        bitField0_ |= 0x00000002;
        hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 hour = 2;</code>
       */
      public Builder clearHour() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hour_ = 0;
        onChanged();
        return this;
      }

      private int minute_ ;
      /**
       * <code>required int32 minute = 3;</code>
       */
      public boolean hasMinute() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 minute = 3;</code>
       */
      public int getMinute() {
        return minute_;
      }
      /**
       * <code>required int32 minute = 3;</code>
       */
      public Builder setMinute(int value) {
        bitField0_ |= 0x00000004;
        minute_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 minute = 3;</code>
       */
      public Builder clearMinute() {
        bitField0_ = (bitField0_ & ~0x00000004);
        minute_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ipv4SrcAddr_ = "";
      /**
       * <code>required string ipv4_src_addr = 4;</code>
       */
      public boolean hasIpv4SrcAddr() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string ipv4_src_addr = 4;</code>
       */
      public java.lang.String getIpv4SrcAddr() {
        java.lang.Object ref = ipv4SrcAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipv4SrcAddr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ipv4_src_addr = 4;</code>
       */
      public com.google.protobuf.ByteString
          getIpv4SrcAddrBytes() {
        java.lang.Object ref = ipv4SrcAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipv4SrcAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ipv4_src_addr = 4;</code>
       */
      public Builder setIpv4SrcAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ipv4SrcAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_src_addr = 4;</code>
       */
      public Builder clearIpv4SrcAddr() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ipv4SrcAddr_ = getDefaultInstance().getIpv4SrcAddr();
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_src_addr = 4;</code>
       */
      public Builder setIpv4SrcAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ipv4SrcAddr_ = value;
        onChanged();
        return this;
      }

      private int l4SrcPort_ ;
      /**
       * <code>required int32 l4_src_port = 5;</code>
       */
      public boolean hasL4SrcPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 l4_src_port = 5;</code>
       */
      public int getL4SrcPort() {
        return l4SrcPort_;
      }
      /**
       * <code>required int32 l4_src_port = 5;</code>
       */
      public Builder setL4SrcPort(int value) {
        bitField0_ |= 0x00000010;
        l4SrcPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 l4_src_port = 5;</code>
       */
      public Builder clearL4SrcPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        l4SrcPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ipv4DstAddr_ = "";
      /**
       * <code>required string ipv4_dst_addr = 6;</code>
       */
      public boolean hasIpv4DstAddr() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string ipv4_dst_addr = 6;</code>
       */
      public java.lang.String getIpv4DstAddr() {
        java.lang.Object ref = ipv4DstAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipv4DstAddr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ipv4_dst_addr = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIpv4DstAddrBytes() {
        java.lang.Object ref = ipv4DstAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipv4DstAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ipv4_dst_addr = 6;</code>
       */
      public Builder setIpv4DstAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ipv4DstAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_dst_addr = 6;</code>
       */
      public Builder clearIpv4DstAddr() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ipv4DstAddr_ = getDefaultInstance().getIpv4DstAddr();
        onChanged();
        return this;
      }
      /**
       * <code>required string ipv4_dst_addr = 6;</code>
       */
      public Builder setIpv4DstAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ipv4DstAddr_ = value;
        onChanged();
        return this;
      }

      private int l4DstPort_ ;
      /**
       * <code>required int32 l4_dst_port = 7;</code>
       */
      public boolean hasL4DstPort() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 l4_dst_port = 7;</code>
       */
      public int getL4DstPort() {
        return l4DstPort_;
      }
      /**
       * <code>required int32 l4_dst_port = 7;</code>
       */
      public Builder setL4DstPort(int value) {
        bitField0_ |= 0x00000040;
        l4DstPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 l4_dst_port = 7;</code>
       */
      public Builder clearL4DstPort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        l4DstPort_ = 0;
        onChanged();
        return this;
      }

      private int inBytes_ ;
      /**
       * <code>required int32 in_bytes = 8;</code>
       */
      public boolean hasInBytes() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 in_bytes = 8;</code>
       */
      public int getInBytes() {
        return inBytes_;
      }
      /**
       * <code>required int32 in_bytes = 8;</code>
       */
      public Builder setInBytes(int value) {
        bitField0_ |= 0x00000080;
        inBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 in_bytes = 8;</code>
       */
      public Builder clearInBytes() {
        bitField0_ = (bitField0_ & ~0x00000080);
        inBytes_ = 0;
        onChanged();
        return this;
      }

      private int outBytes_ ;
      /**
       * <code>required int32 out_bytes = 9;</code>
       */
      public boolean hasOutBytes() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 out_bytes = 9;</code>
       */
      public int getOutBytes() {
        return outBytes_;
      }
      /**
       * <code>required int32 out_bytes = 9;</code>
       */
      public Builder setOutBytes(int value) {
        bitField0_ |= 0x00000100;
        outBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 out_bytes = 9;</code>
       */
      public Builder clearOutBytes() {
        bitField0_ = (bitField0_ & ~0x00000100);
        outBytes_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.NetRecord)
    }

    // @@protoc_insertion_point(class_scope:protobuf.NetRecord)
    private static final org.shahin.protobuf.NetRecordProto.NetRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.shahin.protobuf.NetRecordProto.NetRecord();
    }

    public static org.shahin.protobuf.NetRecordProto.NetRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NetRecord>
        PARSER = new com.google.protobuf.AbstractParser<NetRecord>() {
      @java.lang.Override
      public NetRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.shahin.protobuf.NetRecordProto.NetRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_NetRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_NetRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025proto/net_reord.proto\022\010protobuf\"\264\001\n\tNe" +
      "tRecord\022\014\n\004date\030\001 \002(\t\022\014\n\004hour\030\002 \002(\005\022\016\n\006m" +
      "inute\030\003 \002(\005\022\025\n\ripv4_src_addr\030\004 \002(\t\022\023\n\013l4" +
      "_src_port\030\005 \002(\005\022\025\n\ripv4_dst_addr\030\006 \002(\t\022\023" +
      "\n\013l4_dst_port\030\007 \002(\005\022\020\n\010in_bytes\030\010 \002(\005\022\021\n" +
      "\tout_bytes\030\t \002(\005B%\n\023org.shahin.protobufB" +
      "\016NetRecordProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_NetRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_NetRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_NetRecord_descriptor,
        new java.lang.String[] { "Date", "Hour", "Minute", "Ipv4SrcAddr", "L4SrcPort", "Ipv4DstAddr", "L4DstPort", "InBytes", "OutBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
